# Generated by Django 6.0.1 on 2026-02-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_xpevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='required_level',
            field=models.IntegerField(default=1),
        ),
    ]
