# Generated by Django 6.0.1 on 2026-02-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.CharField(blank=True, default='🏆', help_text='Emoji or icon name', max_length=100),
        ),
        migrations.AddField(
            model_name='achievement',
            name='xp_reward',
            field=models.IntegerField(default=50, help_text='XP awarded when earning this achievement'),
        ),
    ]
