# Generated by Django 6.0.1 on 2026-02-09 17:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_achievement_icon_achievement_xp_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Rich text lesson content'),
        ),
    ]
