# Generated by Django 6.0.1 on 2026-02-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in USD. 0.00 = free course', max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID for this course', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Product ID for this course', max_length=100),
        ),
    ]
