# Generated by Django 6.0.1 on 2026-02-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_price_course_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
