# Generated by Django 6.0.1 on 2026-02-13 14:56

from django.db import migrations, models
from django.utils.text import slugify

def add_codes_to_existing_achievements(apps, schema_editor):
    Achievement = apps.get_model('courses', 'Achievement')
    for achievement in Achievement.objects.all():
        # Generate a code from the name
        code = slugify(achievement.name)
        # Ensure uniqueness by adding a suffix if needed
        original_code = code
        counter = 1
        while Achievement.objects.filter(code=code).exists():
            code = f"{original_code}-{counter}"
            counter += 1
        achievement.code = code
        achievement.save()

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_achievement_icon_achievement_xp_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='code',
            field=models.SlugField(
                help_text="Unique identifier for use in code (e.g., 'first_lesson', 'course_complete')",
                max_length=50,
                default='temp'  # Temporary default
            ),
            preserve_default=False,
        ),
        migrations.RunPython(add_codes_to_existing_achievements),
        migrations.AlterField(
            model_name='achievement',
            name='code',
            field=models.SlugField(
                help_text="Unique identifier for use in code (e.g., 'first_lesson', 'course_complete')",
                max_length=50,
                unique=True  # Now make it unique after populating
            ),
        ),
    ]