# Generated by Django 6.0.1 on 2026-02-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_refund'),
        ('courses', '0015_add_achievement_code'),
    ]

    operations = [
    ]
