# Generated by Django 6.0.1 on 2026-02-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_merge_0014_refund_0015_add_achievement_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['category', 'threshold']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('lessons', 'Lessons Completed'), ('courses', 'Courses Completed'), ('xp', 'Total XP'), ('streak', 'Learning Streak'), ('special', 'Special Achievements')], default='special', help_text='Category of achievement for progress tracking', max_length=50),
        ),
        migrations.AddField(
            model_name='achievement',
            name='threshold',
            field=models.IntegerField(default=0, help_text='Number required to unlock (e.g., 5 lessons, 100 XP)'),
        ),
    ]
