# Generated by Django 6.0.1 on 2026-02-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_add_achievement_criteria'),
        ('courses', '0018_enhance_comment_model'),
    ]

    operations = [
    ]
