# Generated by Django 6.0.1 on 2026-02-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_add_review_model_clean'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_lesson_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_parent_idx',
        ),
    ]
