# Generated by Django 6.0.1 on 2026-02-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_add_review_model_final'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='courses_les_module__4accd4_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_free_preview'], name='courses_les_is_free_a8e681_idx'),
        ),
    ]
