# Generated by Django 6.0.1 on 2026-02-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_add_certificate_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title', max_length=255, null=True, unique=True),
        ),
    ]
