# Generated by Django 6.0.1 on 2026-03-06 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_add_streak_and_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['lesson', 'parent'], name='courses_com_lesson__0a5e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='courses_com_user_id_8d08df_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='courses_pay_user_id_cd4b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_checkout_session_id'], name='courses_pay_stripe__42b9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status'], name='courses_ref_payment_50cd14_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['stripe_refund_id'], name='courses_ref_stripe__149591_idx'),
        ),
    ]
