name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements/development.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Check migrations
        run: |
          python manage.py makemigrations --check --dry-run
